PROXY_MAKER/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls'), name = 'main'),
    path('card/', include('card_manager.urls'), name = 'card_manager'),
    path('accounts/', include('accounts.urls'), name = 'accounts'),
]

accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.urls import include, path

app_name = 'accounts'

urlpatterns = [
  path('', views.IndexView.as_view(), name='index'),
  path('login/', views.Login.as_view(), name='login'),
  path('logout/', views.Logout.as_view(), name='logout'),
  path('user_create/', views.UserCreate.as_view(), name='user_create'),
]

card_manager/urls.py
from django.urls import path
from card_manager import views

app_name = 'card_manager'

urlpatterns = [
    path('', views.card_choice, name='card_choice'),
    path('card_register/', views.card_register, name='card_register'),
    path('pool/', views.card_pool, name='card_pool'),
    path('del/<int:card_id>/', views.card_del, name='card_del'),

    path('decks/', views.deck_list, name='deck_list'),
    path('decks/add/', views.deck_edit, name='deck_add'), 

    path('proxy/', views.ProxyView.as_view(), name='proxy'),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.TopView.as_view(), name='index'),
]

accounts/models.py
from django.db import models

# Create your models here.

card_manager/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

from datetime import datetime
from django.utils import timezone

from django.core.validators import MinLengthValidator, MaxLengthValidator, URLValidator

class UserDecks(models.Model):

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    card_source = models.URLField(validators=[URLValidator])
    name = models.CharField('デッキ名', max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{} , {}".format(self.owner, self.name)

class Deck(models.Model):

    name = models.ForeignKey(UserDecks, on_delete=models.CASCADE)
    card_source = models.URLField(validators=[URLValidator])


class Card(models.Model):

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField('カード名', max_length=255, blank=True)
    card_source = models.URLField(validators=[URLValidator])
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

card_manager/forms.py
from django.forms import ModelForm
from card_manager.models import UserDecks


class UserDecksForm(ModelForm):
    """デッキのフォーム"""
    class Meta:
        model = UserDecks
        fields = ('name', )

accounts/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth import login

from django.views.generic import TemplateView
from django.views.generic import CreateView

from django.http import HttpResponseBadRequest
from django.shortcuts import redirect


class IndexView(TemplateView):
    template_name = "accounts/index.html"

class Login(LoginView):
    """ログインページ"""
    form_class = AuthenticationForm
    template_name = 'accounts/login.html'

class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'main/index.html'

class UserCreate(CreateView):
    """ユーザー登録"""
    template_name = 'accounts/user_create.html'
    form_class = UserCreationForm

    def form_valid(self, form):
        """正しければ登録"""
        try:
            user = form.save(commit=False)
            user.is_active = True
            user.save()
            login(self.request, user)

            return redirect('main:index')

        except:
            return HttpResponseBadRequest()

card_manager/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from card_manager.models import Card, Deck, UserDecks
from django.contrib.auth.models import User

from django.http import HttpResponse
from django.template import loader
from django.views.generic import TemplateView
from card_manager.forms import UserDecksForm

import glob
import sys
import base64
import json
import os
import subprocess
import shutil
from urllib import request as req
from urllib import error
from urllib import parse
import bs4


@login_required
def card_choice(request):

    def crawler(card):

        keyword ='遊戯王' + str(card)

        urlKeyword = parse.quote(keyword)
        url = 'https://www.google.com/search?hl=jp&q={}&btnG=Google+Search&tbs=0&safe=off&tbm=isch'.format(urlKeyword)

        headers = {"User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0",}
        request = req.Request(url=url, headers=headers)
        page = req.urlopen(request)

        html = page.read().decode('utf-8')
        html = bs4.BeautifulSoup(html, "html.parser")
        elems = html.select('.rg_meta.notranslate')
        imageURLs = []
        counter = 0
        for ele in elems:
            ele = ele.contents[0].replace('"','').split(',')
            eledict = dict()
            for e in ele:
                num = e.find(':')
                eledict[e[0:num]] = e[num+1:]
            imageURL = eledict['ou']
            imageURLs.append(imageURL)

        return imageURLs[0:10]

    if request.method == 'GET':
        card = ""
        message = ''

        context = {
            'card_url': parse.quote(card),
            'message': message,
        }

        return render(request, 'card_manager/card.html', context)

    elif request.method == 'POST':
        card = request.POST.get('card', None)
        keyword = '遊戯王 {}'.format(card)
        card_url_list = crawler(card)
        message = card + 'っぽい画像を選んでください'

        context = {
            'card': card,
            'message': message,
            'card_url_list': card_url_list,
        }


        return render(request, 'card_manager/card.html', context)

@login_required
def card_register(request):

    card = Card()

    if request.method == 'POST':
        selected_card = request.POST.get('selected_card', None)
        owner = request.user
        card.owner = owner
        card.card_source = selected_card.split(',')[0]
        card.name = selected_card.split(',')[1]
        card.save()
        print(owner)
        print(selected_card.split(',')[1])

    return redirect('card_manager:card_choice')

@login_required
def card_pool(request):
    user = request.user
    cards = Card.objects.filter(owner=user).order_by('id')
    # decks = Deck.objects.filter(owner=user).order_by('id')
    context = {
        'cards': cards,
        # 'decks': decks,
    }
    return render(request, 'card_manager/card_pool.html', context)

class ProxyView(TemplateView):
    template_name = "card_manager/proxy.html"

def card_del(request, card_id):
    """カードの削除"""
#     return HttpResponse('書籍の削除')
    card = get_object_or_404(Card, pk=card_id)
    card.delete()
    return redirect('card_manager:card_pool')

@login_required
def deck_list(request):
    """デッキの一覧"""
    user = request.user
    decks = UserDecks.objects.filter(owner=user).order_by('id')
    context = {
        'decks': decks,
    }
    return render(request, 'card_manager/deck_list.html', context)

def deck_edit(request, deck_id=None):
    # TODO: リファクタリング
    """デッキの編集"""
    user_id = request.user.id
    owner = User.objects.get(id=user_id)

    if deck_id:   # book_id が指定されている (修正時)
        deck = get_object_or_404(UserDecks, pk=deck_id)
    else:         # book_id が指定されていない (追加時)
        deck = UserDecks()

    if request.method == 'POST':
        form = UserDecksForm(request.POST, instance=deck)  # POST された request データからフォームを作成
        if form.is_valid():    # フォームのバリデーション
            deck = form.save(commit=False)
            deck.owner = owner
            deck.save()
            return redirect('card_manager:deck_list')
    else:    # GET の時
        form = UserDecksForm(instance=deck)  # book インスタンスからフォームを作成

    return render(request, 'card_manager/deck_edit.html', dict(form=form, deck_id=deck_id))

main/views.py
from django.views.generic import TemplateView

class TopView(TemplateView):
    template_name = "main/index.html"

templates/accounts/index.html
{% extends "base.html" %}
{% block extrastyle %}
{% endblock %}

{% block branding %}
Mr. Loto PoC
{% endblock %}

{% block content %}
<h2>登録・ログイン</h2>
<p>本来はトップページのヘッダにリンクがあるようなイメージ</p>
<p>
<li><a href="{% url 'accounts:user_create' %}">ユーザ登録</a> user_create/</li>
<li><a href="{% url 'accounts:login' %}">ユーザログイン</a> login/</li>
</p>

{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% load static %}
{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}" />
{% endblock %}

{% block bodyclass %}login{% endblock %}

{% block breadcrumbs %}
{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="#">PROXY_MAKER PoC</a></h1>
{% endblock %}

{% block content %}
    <div id="content-main">
        {% if form.errors  %}
        <p class="errornote">Your usernamne and password didn't match. Please try again.</p>
        {% endif %}
      <form action="" method="post" id="login-form" role="form">
        {% csrf_token %}
        <div class="form-row">
          <label class="required" for="id_username">ユーザー名:</label><input id="id_username" name="username" type="text" value="" maxlength="256" placeholder="Username" autofocus required/>
        </div>
        <div class="form-row">
          <label class="required" for="id_password">パスワード:</label><input id="id_password" name="password" type="password" value="" maxlength="256" placeholder="Pasword" required/>
        </div>
        <div class="submit-row">
          <label>&nbsp;</label><input type="submit" value="ログイン" />
        </div>
      </form>
    </div>
  <div class="" style="text-align: right;">
    <span><a href="{% url 'accounts:user_create' %}">create a new account</a></span>
    <br>
    <span><a href="{% url 'main:index' %}">HOME</a></span>
  </div>

{% endblock %}

templates/accounts/user_create.html
{% extends "base.html" %}

{% load static %}
{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}" />
{% endblock %}

{% block branding %}
PROXY_MAKER PoC
{% endblock %}

{% block content %}
<form action="" method="POST">
    {{ form.non_field_errors }}
    {% for field in form %}
    <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
        {{ field }}
        {{ field.errors }}
    </div>
    {% endfor %}
    {% csrf_token %}
    <div class="submit-row">
      <label>&nbsp;</label><input type="submit" value="送信" />
    </div>
</form>
{% endblock %}

templates/base.html
{% load i18n static %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}{% get_current_language_bidi as LANGUAGE_BIDI %}
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
{% block extrahead %}{% endblock %}
{% block responsive %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive.css" %}" />
    {% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% static "admin/css/responsive_rtl.css" %}" />{% endif %}
{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}"
  data-admin-utc-offset="{% now "Z" %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% block usertools %}
        {% if has_permission %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% if site_url %}
                    <a href="{{ site_url }}">{% trans 'View site' %}</a> /
                {% endif %}
                {% if user.is_active and user.is_staff %}
                    {% url 'django-admindocs-docroot' as docsroot %}
                    {% if docsroot %}
                        <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                    {% endif %}
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'admin:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% endblock %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'main:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    {% if user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}">logout</a>
    {% else %}
    <a href="{% url 'accounts:login' %}">login</a>
    {% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

templates/card_manager/card.html
{% extends "base.html" %}

{% block branding %}
PROXY MAKER PoC
{% endblock %}

{% load static %} {% block content %} {% csrf_token %}
<link rel="stylesheet" media="all" href={% static "css/style.css" %}>

<h2>カード登録</h2>

{% if user.is_authenticated %}
<p>ユーザID: {{ user.id }}</p>
<p>ユーザ名: {{ user }}</p>
{% endif %}

<p>
  <li><a href="{% url 'card_manager:card_pool' %}"> [カード管理] カードプール</a> /card/pool/</li>
  <li><a href="{% url 'card_manager:deck_list' %}"> [カード管理] デッキ一覧</a> /card/decks/</li>
  <li><a href="{% url 'card_manager:proxy' %}"> [カード管理] プロキシ表示(demo)</a> /card/proxy/</li>
</p>

<form action="" method="post">
  {% csrf_token %}
  <div>
    <label for="card">検索するカード名: </label>
    <input id="card" type="card" name="card" >
  </div>
  <div class="">
    <button class="btn btn-primary btn-lg">検索</button>
  </div>
</form>

<div class="">
  <p>{{ message }}</p>
</div>

<form class="" action="{% url 'card_manager:card_register' %}" method="post">
  {% csrf_token %}
<button class="btn btn-primary btn-lg">カードプールへ追加</button><br>
<span class="card_image">
  {% for card_url in card_url_list %}
  <label>
    <input class="location_radio" type="radio" name="selected_card" value="{{ card_url }},{{ card }}">
    <img class="thumbnail" src="{{ card_url }}" />
  </label>
  {% endfor %}
</span>
</form>

{% endblock %}

templates/card_manager/card_pool.html
{% extends "base.html" %}

{% block branding %}
PROXY MAKER PoC
{% endblock %}

{% load static %} {% block content %}

<h2>カードプール</h2>
{% if user.is_authenticated %}
<p>ユーザID: {{ user.id }}</p>
<p>ユーザ名: {{ user }}</p>
{% endif %}

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">サムネ</th>
      <th scope="col">名前</th>
      <th scope="col">アクション</th>
    </tr>
    </thead>
    <tbody>
    {% for card in cards %}
    <tr>
      <th scope="row"><img src="{{ card.card_source }}" width="150" alt=""/></th>
      <td>{{ card.name }}</td>
      <td>
        <a href="" class="btn btn-outline-primary btn-sm">修正</a>
        <a href="{% url 'card_manager:card_del' card_id=card.id %}" class="btn btn-outline-danger btn-sm">削除</a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/card_manager/deck_edit.html
{% extends "base.html" %}

{% block branding %}
PROXY MAKER PoC
{% endblock %}

{% load static %}

{% block content %}
<form action="{% url 'card_manager:deck_add' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit" class="btn btn-primary">送信</button>
</form>
{% endblock content %}

templates/card_manager/deck_list.html
{% extends "base.html" %}

{% block branding %}
PROXY MAKER PoC
{% endblock %}

{% load static %} {% block content %} {% csrf_token %}

<h2>デッキ一覧</h2>

{% if user.is_authenticated %}
<p>ユーザID: {{ user.id }}</p>
<p>ユーザ名: {{ user }}</p>
{% endif %}

<a href="{% url 'card_manager:deck_add' %}" class="btn btn-primary btn-sm my-3">追加</a>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th scope="col">サムネ</th>
      <th scope="col">名前</th>
      <th scope="col">アクション</th>
    </tr>
    </thead>
    <tbody>
    {% for card in cards %}
    <tr>
      <th scope="row"><img src="{{ card.card_source }}" width="150" alt=""/></th>
      <td>{{ card.name }}</td>
      <td>
        <a href="" class="btn btn-outline-primary btn-sm">修正</a>
        <a href="{% url 'card_manager:card_del' card_id=card.id %}" class="btn btn-outline-danger btn-sm">削除</a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock %}

templates/main/index.html
{% load static %}
<!doctype html>
<html lang="ja">

<head>
	<meta charset="UTF-8">
	<meta name="description" content="カジュアルプレイ用の代理カード作成 などに是非ご活用ください">
	<meta name="viewport" content="width=device-width">
	<title>PROXY MAKER | YGO OCG</title>
	<link rel="stylesheet" media="all" href={% static "css/style.css" %}>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
	<script src={% static 'js/script.js' %}></script>
</head>

<body id="top">
	<div id="wrapper">

		<div id="sidebar">
			<div id="sidebarWrap">
				<h1><a href="#top"><img src={% static "images/logo.png" %} width="87" height="25" alt="logo"></a></h1>
				<nav id="mainnav">
					<p id="menuWrap"><a id="menu"><span id="menuBtn"></span></a></p>
					<div class="panel">
						<ul>
							<li><a href="{% url 'card_manager:card_choice' %}">PROXY MAKER</a></li>
							{% if user.is_authenticated %}
							<li><a href="{% url 'accounts:logout' %}">LOGOUT</a></li>
							{% else %}
							<li><a href="{% url 'accounts:login' %}">LOGIN/SIGNIN</a></li>
							{% endif %}
							<li><a href="#sec01">ABOUT</a></li>
							<li><a href="#sec02">SAMPLE DECKS</a></li>
							<li><a href="#sec03">HOW TO USE</a></li>
						</ul>
						<ul id="sns">
							<li><a href="#" target="_blank"><img src={% static 'images/iconFb.png' %} width="20" height="20" alt="FB"></a></li>
							<li><a href="#" target="_blank"><img src={% static 'images/iconTw.png' %} width="20" height="20" alt="twitter"></a></li>
							<li><a href="#" target="_blank"><img src={% static 'images/iconInsta.png' %} width="20" height="20" alt="Instagram"></a></li>
							<li><a href="#" target="_blank"><img src={% static 'images/iconYouTube.png' %} width="20" height="20" alt="You Tube"></a></li>
						</ul>
					</div>
				</nav>
			</div>
		</div>

		<div id="content">
			<h1><span>PROXY_MAKER</span></h1>
			{% if user.is_authenticated %}
			<p>ユーザID: {{ user.id }}</p>
			<p>ユーザ名: {{ user }}</p>
			{% endif %}
			<div class="">
				<p>
					<li><a href="{% url 'accounts:index' %}"> [アカウント管理] 登録・ログイン機能</a> /accounts/</li>
				</p>
				<p>
					<li><a href="{% url 'card_manager:card_choice' %}"> [プロキシメーカー] カード検索とか</a> /card/</li>
				</p>
			</div>
			<!-- <p id="mainImg"><img src={% static "images/mainImg.jpg" %} width="800" height="168" alt=""></p> -->
			<!-- MESSAGE -->
			<section id="sec01">
				<header>
					<h2><span>ABOUT</span></h2>
				</header>
				<div class="innerS">
					このサイトは、 TCGのプロキシカード を簡単に作成することが出来る「プロキシカードメーカー」を提供するサイトです。 高額＆品薄で入手困難なカードのプロキシ作成 発売前のカードの試運転 カジュアルプレイ用の代理カード作成 などに是非ご活用ください。
				</div>
			</section>
			<!-- // MESSAGE -->
			<!-- BRAND -->
			<section id="sec02">
				<header>
					<h2><span>SAMPLE DECKS</span></h2>
				</header>
				<div class="inner">
					<ul class="col4">
						<li>
							<p class="img"><a href=""><img src={% static "images/logo01.png" %} width="168" height="168" alt=""></a></p>
							<p>強いデッキ</p>
						</li>
						<li>
							<p class="img"><a href=""><img src={% static "images/logo02.png" %} width="168" height="168" alt=""></a></p>
							<p>環境最強</p>
						</li>
						<li>
							<p class="img"><a href=""><img src={% static "images/logo03.png" %} width="168" height="168" alt=""></a></p>
							<p>ネタ系</p>
						</li>
						<li>
							<p class="img"><a href=""><img src={% static "images/logo04.png" %} width="168" height="168" alt=""></a></p>
							<p>ワンキル</p>
						</li>
					</ul>
				</div>
			</section>
			<!-- // BRAND -->
			<!-- PROJECT -->
			<section id="sec03">
				<header>
					<h2><span>HOW TO USE</span></h2>
				</header>
				<div class="inner">
					<div class="article">
						<img src={% static "images/photo14.jpg" %} width="370" height="224" alt="">
						<p>このサイトは、 TCGのプロキシカード を簡単に作成することが出来る「プロキシカードメーカー」を提供するサイトです。 高額＆品薄で入手困難なカードのプロキシ作成 発売前のカードの試運転 カジュアルプレイ用の代理カード作成 などに是非ご活用ください。</p>
						<p>このサイトは、 TCGのプロキシカード を簡単に作成することが出来る「プロキシカードメーカー」を提供するサイトです。 高額＆品薄で入手困難なカードのプロキシ作成 発売前のカードの試運転 カジュアルプレイ用の代理カード作成 などに是非ご活用ください。</p>
					</div>
					<div class="article">
						<img src={% static "images/photo15.jpg" %} width="370" height="224" alt="">
						<p>このサイトは、 TCGのプロキシカード を簡単に作成することが出来る「プロキシカードメーカー」を提供するサイトです。 高額＆品薄で入手困難なカードのプロキシ作成 発売前のカードの試運転 カジュアルプレイ用の代理カード作成 などに是非ご活用ください。</p>
						<p>このサイトは、 TCGのプロキシカード を簡単に作成することが出来る「プロキシカードメーカー」を提供するサイトです。 高額＆品薄で入手困難なカードのプロキシ作成 発売前のカードの試運転 カジュアルプレイ用の代理カード作成 などに是非ご活用ください。</p>
					</div>
				</div>
			</section>
			<!-- // PROJECT -->

			<footer id="footer">
				Copyright (C) 2018 sonoda umi All Rights Reserved. Design by <a href="http://f-tpl.com" target="_blank">http://f-tpl.com</a>
			</footer>

		</div>
	</div>

</body>

</html>